// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuh1JBF8GGnc4t55po306YJP8qrQVvrgo',
    appId: '1:406860686935:web:98727857a6d52e7e67e512',
    messagingSenderId: '406860686935',
    projectId: 'flutter-app-97c11',
    authDomain: 'flutter-app-97c11.firebaseapp.com',
    storageBucket: 'flutter-app-97c11.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB89xkDtapx_gEa5CbELAp7V5iobgHPiXQ',
    appId: '1:406860686935:android:f78cbd24e9bc909c67e512',
    messagingSenderId: '406860686935',
    projectId: 'flutter-app-97c11',
    storageBucket: 'flutter-app-97c11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzh1JSKsvn7C_S63lQyry3ov8uqHS3VLU',
    appId: '1:406860686935:ios:49355d234d92a40067e512',
    messagingSenderId: '406860686935',
    projectId: 'flutter-app-97c11',
    storageBucket: 'flutter-app-97c11.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzh1JSKsvn7C_S63lQyry3ov8uqHS3VLU',
    appId: '1:406860686935:ios:49355d234d92a40067e512',
    messagingSenderId: '406860686935',
    projectId: 'flutter-app-97c11',
    storageBucket: 'flutter-app-97c11.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuh1JBF8GGnc4t55po306YJP8qrQVvrgo',
    appId: '1:406860686935:web:a44d76cd1d8b7f5967e512',
    messagingSenderId: '406860686935',
    projectId: 'flutter-app-97c11',
    authDomain: 'flutter-app-97c11.firebaseapp.com',
    storageBucket: 'flutter-app-97c11.firebasestorage.app',
  );
}
